version: '3'

services:
  holdem_front:
    container_name: holdem_front
    build: ./frontend
    restart: always
    networks:
      - holdem

  holdem_back:
    container_name: holdem_back
    build: ./backend
    restart: always
    networks:
      - holdem
  
  holdem_nginx:
    container_name: nginx
    restart: always
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - holdem
    depends_on:
      - holdem_back

networks:
  holdem:
    driver: bridge
