swagger: "2.0" 
info: 
  description: "Holdem calculator api" 
  version: "0.1.0" 
  title: "Holdem API" 
host: "__"
tags:
  - name: "On progress" 
    description: "on progress"
    
paths:
  /normal/equity:
    post:
      summary: "Send Game Infomation"
      produces:
        - application/json
      parameters:
        - $ref: "#/parameters/Type_Urlencoded"
        - $ref: "#/parameters/playTime"
        - $ref: "#/parameters/fixedSharedCardnum"
        - $ref: "#/parameters/fixedSharedCard"
        - $ref: "#/parameters/playernum"
        - $ref: "#/parameters/playerRangenum"
        - $ref: "#/parameters/playerRange"
        
      responses:
        200:
          description: "return { success: true, key: GameId }"
        500:
          description: "return \"Impossible Range Setting\""
    get:
      summary: "Calculate Equity & Hand (by Fixed Game Info)"
      produces:
        - application/json
      parameters:
        - $ref: "#/parameters/Type_Urlencoded"
        - $ref: "#/parameters/GameId"
      responses:
        200:
          description: "return { GameResultList[GameId] (GameResult) }"
          schema:
            $ref: "#/definitions/GameResult"

          
definitions:
  GameResult:
    type: object
    properties:
      gameNum:
        type: integer
        description: 전체 게임 횟수
      winNum:
        type: number
        description: percentage 를 고려한 전체 승리 수치
      playerResult:
        type: object
        properties:
          soloWin:
            type: integer
            description: 해당 플레이어의 단독 승리 횟수
          drawWin:
            type: number
            description: 해당 플레이어를 포함한 두 명 이상이 동시에 이긴 횟수
          straightflush:
            type: integer
            description: 해당 플레이어의 최상위 패가 스트레이트 플러시인 게임의 수
          fourcard:
            type: integer
            description: 해당 플레어의 최상위 패가 포카드인 게임의 수
          fullhouse:
            type: integer
            description: 해당 플레어의 최상위 패가 풀하우스인 게임의 수
          flush:
            type: integer
            description: 해당 플레어의 최상위 패가 플러시인 게임의 수
          straight:
            type: integer
            description: 해당 플레어의 최상위 패가 스트레이트인 게임의 수
          triple:
            type: integer
            description: 해당 플레어의 최상위 패가 트리플인 게임의 수
          twopair:
            type: integer
            description: 해당 플레어의 최상위 패가 투 페어인 게임의 수
          onepair:
            type: integer
            description: 해당 플레어의 최상위 패가 원 페어인 게임의 수
          top:
            type: integer
            description: 해당 플레어의 최상위 패가 탑인 게임의 수
            
parameters:

  Type_Urlencoded:
    name: Content-Type
    in: header
    type: string
    required: true
    description: (must be) application/x-www-form-urlencoded
    
  GameId:
    name: GameId
    in: formData
    type: integer
    required: true
    description: 요청 보낸 사용자 식별
    
  playTime:
    name: playTime
    in: formData
    type: integer
    required: true
    description: 실행 시간(초)
  fixedSharedCardnum:
    name: fixedSharedCardnum
    in: formData
    type: integer
    required: true
    description: 고정된 공유 카드 수
  # [1, 2, 3, 4, 5]
  fixedSharedCard:
    name: fixedSharedCard
    in: formData
    type: array
    items:
      type: integer
    required: true
    description: 정해진 공유 카드(0~5장)
  playernum:
    name: playernum
    in: formData
    type: integer
    required: true
    description: 참가자 수
  playerRangenum:
    name: playerRangenum
    in: formData
    type: array
    items:
      type: integer
    required: true
    description: 참가자별 range 에 포함되는 pair 수
  # [(player 1 range)[[13, 13, 0.33(percentage)], [12, 12, 1], ...], (player 2 range)[...], [...], ...]
  playerRange:
    name: playerRange
    in: formData
    type: array
    items:
      type: array
      items:
        type: array
        items:
          type: integer
    required: true
    description: 참가자별 hand range -> [hand1, hand2, percentage]